id: P106F3044
initial_creation_type: ocr
source_metadata:
  volumes:
    1b807f1020d947d39a3f7dcc3f4a5064:
      base_file: v062.txt
      image_group_id: I1PD95907
      title: དབུ་མའི་རྒྱན་གྱི་འགྲེལ་པ།
      total_pages: 1557
      volume_number: 62
